package com.cyb.tms.entity;
// Generated May 17, 2016 12:38:28 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.cyb.tms.entity.base.BaseEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TmsCodeReview generated by hbm2java
 */
@Entity
@Table(name = "tms_code_review", catalog = "TaskManagement")
public class TmsCodeReview extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5889958340304604686L;
	private Long reviewId;
	private TmsSubtask tmsSubtask;
	private TmsUsers tmsUsersByDeveloper;
	private TmsUsers tmsUsersByFixedBy;
	private TmsUsers tmsUsersByReviewer;
	private String commentType;
	private String comments;
	private Date commentsFixedDate;
	private String fileName;
	private String pullRequest;
	private Date pullRequestDate;
	private Date reviewDate;
	private String reviewerType;

	

	public TmsCodeReview() {
	}

	public TmsCodeReview(Long reviewId, TmsSubtask tmsSubtask, TmsUsers tmsUsersByDeveloper, TmsUsers tmsUsersByFixedBy,
			TmsUsers tmsUsersByReviewer, String commentType, String comments, Date commentsFixedDate, String fileName,
			String pullRequest, Date pullRequestDate, Date reviewDate, String reviewerType) {
		super();
		this.reviewId = reviewId;
		this.tmsSubtask = tmsSubtask;
		this.tmsUsersByDeveloper = tmsUsersByDeveloper;
		this.tmsUsersByFixedBy = tmsUsersByFixedBy;
		this.tmsUsersByReviewer = tmsUsersByReviewer;
		this.commentType = commentType;
		this.comments = comments;
		this.commentsFixedDate = commentsFixedDate;
		this.fileName = fileName;
		this.pullRequest = pullRequest;
		this.pullRequestDate = pullRequestDate;
		this.reviewDate = reviewDate;
		this.reviewerType = reviewerType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Long reviewId) {
		this.reviewId = reviewId;
	}
   
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TASK_ID", nullable = false)
	public TmsSubtask getTmsSubtask() {
		return this.tmsSubtask;
	}

	public void setTmsSubtask(TmsSubtask tmsSubtask) {
		this.tmsSubtask = tmsSubtask;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEVELOPER", nullable = false)
	public TmsUsers getTmsUsersByDeveloper() {
		return this.tmsUsersByDeveloper;
	}

	public void setTmsUsersByDeveloper(TmsUsers tmsUsersByDeveloper) {
		this.tmsUsersByDeveloper = tmsUsersByDeveloper;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIXED_BY")
	public TmsUsers getTmsUsersByFixedBy() {
		return this.tmsUsersByFixedBy;
	}

	public void setTmsUsersByFixedBy(TmsUsers tmsUsersByFixedBy) {
		this.tmsUsersByFixedBy = tmsUsersByFixedBy;
	}

	@Column(name = "COMMENT_TYPE", length = 45)
	public String getCommentType() {
		return this.commentType;
	}

	public void setCommentType(String commentType) {
		this.commentType = commentType;
	}

	@Column(name = "COMMENTS", length = 45)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "COMMENTS_FIXED_DATE", length = 10)
	public Date getCommentsFixedDate() {
		return this.commentsFixedDate;
	}

	public void setCommentsFixedDate(Date commentsFixedDate) {
		this.commentsFixedDate = commentsFixedDate;
	}

	@Column(name = "FILE_NAME", length = 45)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "PULL_REQUEST", length = 45)
	public String getPullRequest() {
		return this.pullRequest;
	}

	public void setPullRequest(String pullRequest) {
		this.pullRequest = pullRequest;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REVIEW_DATE", length = 10)
	public Date getReviewDate() {
		return this.reviewDate;
	}

	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REVIEWER")
	public TmsUsers getTmsUsersByReviewer() {
		return tmsUsersByReviewer;
	}
	
	public void setTmsUsersByReviewer(TmsUsers tmsUsersByReviewer) {
		this.tmsUsersByReviewer = tmsUsersByReviewer;
	}

	@Column(name = "REVIEWER_TYPE", nullable = false, length = 45)
	public String getReviewerType() {
		return this.reviewerType;
	}

	public void setReviewerType(String reviewerType) {
		this.reviewerType = reviewerType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PULL_REQUEST_DATE", length = 10)
	public Date getPullRequestDate() {
		return this.pullRequestDate;
	}

	public void setPullRequestDate(Date pullRequestDate) {
		this.pullRequestDate = pullRequestDate;
	}
	
		
}
