package com.cyb.tms.entity;
// Generated May 19, 2016 12:17:39 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.cyb.tms.entity.base.BaseEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TmsModule generated by hbm2java
 */
@Entity
@Table(name = "tms_module", catalog = "TaskManagement")
public class TmsModule extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4790750859389643809L;
	private Long id;
	private TmsProject tmsProject;
	private String moduleName;
	private String moduleDescription;
	private Set<TmsStoryMst> tmsStoryMsts = new HashSet<TmsStoryMst>(0);

	public TmsModule() {
	}

	public TmsModule(TmsProject tmsProject, String moduleName, String moduleDescription,
			Set<TmsStoryMst> tmsStoryMsts) {
		this.tmsProject = tmsProject;
		this.moduleName = moduleName;
		this.moduleDescription = moduleDescription;
		this.tmsStoryMsts = tmsStoryMsts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID")
	public TmsProject getTmsProject() {
		return this.tmsProject;
	}

	public void setTmsProject(TmsProject tmsProject) {
		this.tmsProject = tmsProject;
	}

	@Column(name = "MODULE_NAME", length = 45)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "MODULE_DESCRIPTION", length = 100)
	public String getModuleDescription() {
		return this.moduleDescription;
	}

	public void setModuleDescription(String moduleDescription) {
		this.moduleDescription = moduleDescription;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmsModule")
	public Set<TmsStoryMst> getTmsStoryMsts() {
		return this.tmsStoryMsts;
	}

	public void setTmsStoryMsts(Set<TmsStoryMst> tmsStoryMsts) {
		this.tmsStoryMsts = tmsStoryMsts;
	}


}
