package com.cyb.tms.entity;
// Generated May 19, 2016 12:17:39 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.cyb.tms.entity.base.BaseEntity;

/**
 * TmsUserModuleSprint generated by hbm2java
 */
@Entity
@Table(name = "tms_user_module_sprint", catalog = "TaskManagement")
public class TmsUserModuleSprint extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1750518728362272524L;
	private long id;
	private TmsModule tmsModule;
	private TmsSprintMst tmsSprintMst;
	private TmsUsers tmsUsers;

	public TmsUserModuleSprint() {
	}

	public TmsUserModuleSprint(long id) {
		this.id = id;
	}

	public TmsUserModuleSprint(long id, TmsModule tmsModule, TmsSprintMst tmsSprintMst, TmsUsers tmsUsers) {
		this.id = id;
		this.tmsModule = tmsModule;
		this.tmsSprintMst = tmsSprintMst;
		this.tmsUsers = tmsUsers;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODULE")
	public TmsModule getTmsModule() {
		return this.tmsModule;
	}

	public void setTmsModule(TmsModule tmsModule) {
		this.tmsModule = tmsModule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPRINT")
	public TmsSprintMst getTmsSprintMst() {
		return this.tmsSprintMst;
	}

	public void setTmsSprintMst(TmsSprintMst tmsSprintMst) {
		this.tmsSprintMst = tmsSprintMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER")
	public TmsUsers getTmsUsers() {
		return this.tmsUsers;
	}

	public void setTmsUsers(TmsUsers tmsUsers) {
		this.tmsUsers = tmsUsers;
	}

}
